run:
  timeout: 15m
  tests: true

linters:
  enable:
    - deadcode
    - errcheck
    - funlen
    - gocritic
    - gofmt
    - goheader
    - goimports
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - staticcheck
        - unused
        - varcheck
        - funlen
    - path: doc.go
      linters:
        - goheader

linters-settings:
  goheader:
    template: |-
        Use of this source code is governed by a BSD-style
        license that can be found in the LICENSE file.
